### ISSUE TITLE
Going to Profile from the side drawer crashes the application

### ISSUE THREAD

**Issue by MarcusBoay** [CMPUT301W19T11/Atheneum#93] opened 2019-03-08 05:59 UTC
Going to Profile from the side drawer crashes the application. This happened on requestSearch branch for me but someone else is experiencing this issue on master.

Stack trace:
```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.atheneum, PID: 12231
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.example.atheneum.models.User.getUserName()' on a null object reference
        at com.example.atheneum.fragments.ViewProfileFragment.onCreateView(ViewProfileFragment.java:74)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6111)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)```

_Originally posted by @MarcusBoay in https://github.com/CMPUT301W19T11/Atheneum/pull/92#issuecomment-470811666_

**Comment by siyuamymi** [comment] 2019-03-08 06:32
On master branch going to the profile from nav drawer crashes the app. However, if you go to search and click on a profile, then go to your own profile from nav drawer seems to be ok and the program doesn't crash.

**Comment by siyuamymi** [comment] 2019-03-08 17:10
I will close this issue since its a duplicate of https://github.com/CMPUT301W19T11/Atheneum/issues/68

**Closed by siyuamymi** 2019-03-08 17:10 UTC
Labels: bug, duplicate
