### ISSUE TITLE
Notifications for different users who have logged onto same device appear

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#146] opened 2019-03-16 03:08 UTC
**Describe the bug**

**To Reproduce**
1. Have at least two accounts in the App. Log into both accounts then promptly log out.
2. Log into the app again with the first account.
3. Make a request on a book that the second account owns.
4. Verify that a notification meant for the second account appears while logged into the first account.

**Expected behavior**
Expected to not see notifications for the second account until logged into the second account.

**Smartphone (please complete the following information):**
 - Device: Huawei Nova Plus
 - OS: Android

**Additional context**
Probably a problem with not properly handling observers in the MainActivity for the NotificationLiveData.

Was on 511bc3cb3d418c296f3d2d1aa1d5588a16da9c43  when this happened. I noticed that I still had a userDeviceToken in the Database though. Not sure if that impacts anything.

**Comment by MarcusBoay** [comment] 2019-03-16 03:14
I can't seem to reproduce this with the branch for #143

**Comment by ishchow** [comment] 2019-03-16 03:16
@MarcusBoay oh, that was the branch I noticed it on. Weird.

**Comment by MarcusBoay** [comment] 2019-03-16 03:18
Could you uninstall the app and reinstall it on the branch for #143 to see if the bug can be reproduced then?

**Comment by ishchow** [comment] 2019-03-16 04:24
@MarcusBoay I uninstalled the app, pulled the branch for #143 and tried this again. I caught the behavior on video this time: [link](https://drive.google.com/open?id=1Jyq9Aks0c5rDJFeepKcsJwgykX1TkZ-L).

**Comment by MarcusBoay** [comment] 2019-03-16 04:36
Am I missing something? The video didn't show the bugged behavior.

**Comment by ishchow** [comment] 2019-03-16 04:54
Whoops, that was the wrong video. [Actual video](https://drive.google.com/open?id=1xmVtmsVQyGsLW0r9hns5U3XHSkjy9sPq).

**Comment by MarcusBoay** [comment] 2019-03-17 03:51
Turns out the bug was probably from creating multiple LiveData/ViewModel objects and its respective listener. The usage of LiveData/ViewModel for notifications was improper and is fixed in #143

**Closed** 2019-03-17 05:37 UTC
Labels: bug
